### ISSUE TITLE
Enable download instead of copy-paste

### ISSUE THREAD

**Issue by chipaudette** [Tympan/Tympan_Audio_Design_Tool#2]
Assuming that the webpage/GUI/index.html work correctly, you wire up a bunch of nodes and then hit "export".  This presents a pop-up window with code that you copy-paste into an Arduino window.  That's fine enough, I guess.  But, I'd much prefer it if the browser would simply download a *.ino file to your computer with all you code in there.  Can this be done?  If so, this also offers up the opportunity to download a ZIP that contains multiple Arduino code files, which might end up being more readable.

**Comment by kxm-creare** [comment]
See pull request https://github.com/Tympan/Tympan_Audio_Design_Tool/pull/7

Functionally this works, but may not be exactly what you're looking for stylistically.  Let me know.  Briefly, the .zip option looks doable, we'd just need to add a zip library to our repo.

**Comment by kxm-creare** [comment]
.zip option is complete as of pull request #8.
